# Generated by Django 2.2.5 on 2020-10-30 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('announce', models.CharField(max_length=250, verbose_name='Описание')),
                ('date', models.DateTimeField(verbose_name='Время создания')),
            ],
        ),
    ]
