# Generated by Django 2.2.5 on 2020-10-31 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('json_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='announce',
            new_name='description',
        ),
    ]
